"""
Expedition = the "expedition progression" loop: everything here is thrown
away when the run ends, except whatever gets converted into permanent
rewards (gold, XP, InventoryItems) at that point.

The dungeon graph itself is generated by bot/game/dungeon/generator.py and
stored here as JSON so an in-progress run survives a bot restart -- the
player can resume exactly where they left off.
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import JSON, BigInteger, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from bot.database.models.base_model import Base
from bot.database.models.enums import ExpeditionStatus


class Expedition(Base):
    __tablename__ = "expeditions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    player_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("players.id", ondelete="CASCADE")
    )

    region: Mapped[str] = mapped_column(String(64))  # e.g. "Whispering Forest"
    status: Mapped[ExpeditionStatus] = mapped_column(default=ExpeditionStatus.ACTIVE)

    # Node graph produced by the dungeon generator: nodes, edges, room types.
    graph: Mapped[dict] = mapped_column(JSON, default=dict)
    current_node_id: Mapped[str] = mapped_column(String(32), default="start")

    # Full serialized Battle state (see bot/game/combat/serialization.py) when
    # the player is mid-fight, else None. This is what lets a battle survive
    # a bot restart or the player disappearing mid-fight -- nothing about an
    # in-progress battle is ever held only in memory between interactions.
    combat_state: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Expedition-only state -- wiped when the run ends, unlike Player/Inventory.
    current_hp: Mapped[int] = mapped_column(Integer, default=100)
    temp_buffs: Mapped[list] = mapped_column(JSON, default=list)   # blessings
    temp_curses: Mapped[list] = mapped_column(JSON, default=list)
    relics: Mapped[list] = mapped_column(JSON, default=list)      # expedition-only relics
    gold_collected: Mapped[int] = mapped_column(Integer, default=0)

    started_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    ended_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    player: Mapped["Player"] = relationship(back_populates="expeditions")  # noqa: F821

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Expedition id={self.id} region={self.region!r} status={self.status}>"
