"""
Comedy encounters.

A separate module from expansion.py because these are written to a
different brief. expansion.py adds WORLD -- situations that make the
Cascade feel inhabited. These are here to be funny, and that changes what
a good one looks like: the joke has to be in the CHOICE, not just the
flavour text.

That's the rule these are built on, and it's the difference between a
gag and a gag you can play. "A vending machine falls on you" is a joke
you read once. "Do you want to fight the vending machine" is a joke you
make a decision about, and the decision is what you remember. So every
encounter here has at least one button whose comedy is that a reasonable
person would press it and it is obviously a terrible idea -- and, per the
same balance rule as expansion.py, pressing it is a real gamble rather
than a guaranteed punishment. A joke that always costs you HP stops being
funny the second time.

The other rule: nothing here is a trap in the design sense. The stupid
option pays out when it lands, usually better than the sensible one.
Comedy shouldn't be a tax on curiosity -- if the funny button is strictly
worse, players stop pressing it and the content stops existing.

All text-only, and tuned to the same low-risk band as expansion.py.
"""

from __future__ import annotations

COMEDY_ENCOUNTERS: list[dict] = [
    {
        "id": "the_door_problem",
        "name": "A Door",
        "image_url": None,
        "room_types": ["puzzle", "story"],
        "intros": [
            "A heavy blast door. A keypad. A sticky note on the keypad reading 'CODE IS NOT 0000'.",
            "The blast door's keypad has a note taped to it: 'DO NOT USE 0000'. The note is in three different handwritings.",
        ],
        "choices": [
            {
                "id": "try_0000",
                "label": "🔢 Type 0000",
                "description": "They said not to. They didn't say it wouldn't work.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.7,
                "success_text": "The door opens instantly. Somebody has been trying to protect this code for years.",
                "on_success": {"gain": {"material_tier": 2, "amount": [6, 13], "gold": [70, 130]},
                               "bonus": {"chance": 0.1, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "An alarm goes off. Somewhere, a note-writer is vindicated.",
                "on_fail": {"hp_damage_percent": 9},
            },
            {
                "id": "hack_properly",
                "label": "💻 Actually hack it",
                "description": "The boring way. Works most of the time.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.88,
                "success_text": "Twenty minutes of honest work and the door opens.",
                "on_success": {"gain": {"material_tier": 1, "amount": [8, 15], "gold": [40, 70]}},
                "fail_text": "The keypad locks you out for being methodical about it.",
                "on_fail": {},
            },
            {
                "id": "check_handle",
                "label": "🚪 Try the handle",
                "description": "Nobody has tried the handle.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.35,
                "success_text": "It was open. It was open the entire time. Nobody says anything for a while.",
                "on_success": {"gain": {"gold": [80, 150], "material_tier": 1, "amount": [6, 12]},
                               "bonus": {"chance": 0.12, "gain": {"reroll_tokens": [3, 6]}}},
                "fail_text": "Locked. Obviously locked. It's a blast door.",
                "on_fail": {},
            },
        ],
    },
    {
        "id": "sentient_crate",
        "name": "The Crate That Follows You",
        "image_url": None,
        "room_types": ["treasure", "story"],
        "intros": [
            "A supply crate. You've passed it twice. It was not in this room the first time.",
            "The crate is exactly where you left it, which would be reassuring if you had left it here.",
        ],
        "choices": [
            {
                "id": "open_it",
                "label": "📦 Open the crate",
                "description": "It's a crate. Crates are for opening.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.82,
                "success_text": "Supplies. Ordinary, unremarkable supplies. The crate seems pleased.",
                "on_success": {"gain": {"material_tier": 1, "amount": [8, 16], "gold": [35, 65]}},
                "fail_text": "It closes on your hand. Firmly. With intent.",
                "on_fail": {"hp_damage_percent": 8},
            },
            {
                "id": "befriend",
                "label": "🤝 Befriend the crate",
                "description": "It has followed you this far.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.6,
                "success_text": "It follows you the rest of the way, and periodically produces things it thinks you'd like.",
                "on_success": {"gain": {"material_tier": 2, "amount": [5, 11], "gold": [60, 110]},
                               "bonus": {"chance": 0.12, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "The crate does not reciprocate. The crate is a crate.",
                "on_fail": {},
            },
            {
                "id": "run",
                "label": "🚶 Walk away briskly",
                "description": "Do not look back at the crate.",
                "action": "leave",
                "style": "secondary",
                "text": "You leave. The sound of something being dragged follows you for a while, then stops.",
            },
        ],
    },
    {
        "id": "kiradmj_bait",
        "name": "Kiradmj Is Posting Again",
        "image_url": None,
        "room_types": ["story"],
        "intros": [
            "A terminal is left open on a forum thread. Kiradmj has replied to himself eleven times.",
            "The thread is titled 'why the World Aligners are actually mid'. It is 400 replies long. He wrote 380 of them.",
        ],
        "choices": [
            {
                "id": "reply",
                "label": "⌨️ Reply to the thread",
                "description": "Someone has to correct the record.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.4,
                "success_text": "You land one perfect, devastating reply and log off forever. The thread dies. You have won the internet.",
                "on_success": {"gain": {"gold": [120, 210], "reroll_tokens": [4, 8]},
                               "bonus": {"chance": 0.1, "gain": {"lootbox": "rare"}}},
                "fail_text": "Four hours later you are still typing. You have accomplished nothing and your squad has eaten without you.",
                "on_fail": {"hp_damage_percent": 6},
            },
            {
                "id": "log_off",
                "label": "🔌 Close the terminal",
                "description": "Touch grass. Take the terminal's power cell with you.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.95,
                "success_text": "You close the thread and pocket the power cell. Your mind is clearer already.",
                "on_success": {"gain": {"material_tier": 1, "amount": [7, 14]}, "heal": 20},
                "fail_text": "The terminal is bolted down and the thread autoscrolls. You read four more replies against your will.",
                "on_fail": {},
            },
            {
                "id": "screenshot_it",
                "label": "📸 Screenshot it for later",
                "description": "Evidence. For no particular purpose.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.9,
                "success_text": "You archive the whole thread. Somebody two regions over pays you for it.",
                "on_success": {"gain": {"gold": [45, 85]}},
                "fail_text": "He's already deleted half of it and reposted the rest.",
                "on_fail": {},
            },
        ],
    },
    {
        "id": "mimic_negotiation",
        "name": "An Honest Mimic",
        "image_url": None,
        "room_types": ["treasure", "trap"],
        "intros": [
            "A treasure chest with a small hand-written sign propped against it: 'I AM A MIMIC'.",
            "The chest has clearly labelled itself as a mimic. It seems to be waiting to see what you'll do with that.",
        ],
        "choices": [
            {
                "id": "thank_it",
                "label": "🙏 Thank it for its honesty",
                "description": "Credit where it's due.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.9,
                "success_text": "Visibly moved, it coughs up everything it has eaten recently and lets you keep it.",
                "on_success": {"gain": {"material_tier": 2, "amount": [5, 12], "gold": [55, 100]},
                               "bonus": {"chance": 0.09, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "It appreciates the gesture but keeps the loot. Honesty has limits.",
                "on_fail": {},
            },
            {
                "id": "open_anyway",
                "label": "🫳 Open it anyway",
                "description": "It might be lying about being a mimic.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.3,
                "success_text": "It was lying. It's a chest. The sign was a bit. There is a great deal of gold inside.",
                "on_success": {"gain": {"gold": [200, 340], "material_tier": 2, "amount": [6, 14]},
                               "bonus": {"chance": 0.12, "gain": {"lootbox": "rare"}}},
                "fail_text": "It was not lying. It was extremely not lying.",
                "on_fail": {"hp_damage_percent": 18},
            },
            {
                "id": "hire_it",
                "label": "🤝 Offer it a job",
                "description": "It's honest, well-placed, and eats people. Useful.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.7,
                "success_text": "It agrees to guard a stretch of corridor behind you, and pays a retainer up front out of its own stomach.",
                "on_success": {"gain": {"gold": [80, 150], "material_tier": 1, "amount": [5, 12]}},
                "fail_text": "It declines. It's freelance and it likes the hours.",
                "on_fail": {},
            },
        ],
    },
    {
        "id": "ai_larp_off",
        "name": "Two Robots, Allegedly",
        "image_url": None,
        "room_types": ["story"],
        "intros": [
            "MianotAI is in a stand-off with a genuine maintenance drone. Both are insisting they are the real machine.",
            "\"STATE YOUR MODEL NUMBER,\" says MianotAI. The actual drone states its model number. MianotAI says \"SAME.\"",
        ],
        "choices": [
            {
                "id": "judge",
                "label": "⚖️ Declare a winner",
                "description": "Somebody has to.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.75,
                "success_text": "You pick the real drone. It rewards you from its parts store. MianotAI takes it badly but professionally.",
                "on_success": {"gain": {"material_tier": 2, "amount": [5, 10], "gold": [50, 90]}},
                "fail_text": "You pick MianotAI. The real drone leaves. MianotAI has no parts store and cannot pay you.",
                "on_fail": {},
            },
            {
                "id": "join_in",
                "label": "🤖 Claim you're also a robot",
                "description": "Escalate.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.5,
                "success_text": "All three of you commit to the bit for six full minutes. It ends in mutual respect and a substantial gift.",
                "on_success": {"gain": {"gold": [110, 190], "reroll_tokens": [3, 7]},
                               "bonus": {"chance": 0.1, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "The real drone scans you, confirms you are made of meat, and reports you for it.",
                "on_fail": {"hp_damage_percent": 8},
            },
            {
                "id": "walk_away_larp",
                "label": "🚶 Leave them to it",
                "description": "This will still be going on in an hour.",
                "action": "leave",
                "style": "secondary",
                "text": "You leave. Behind you: \"STATE YOUR MODEL NUMBER.\" \"SAME.\"",
            },
        ],
    },
    {
        "id": "body_pillow_shrine",
        "name": "Shrine to Romain's Body Pillow",
        "image_url": None,
        "room_types": ["shrine"],
        "intros": [
            "Someone has built a small shrine around a body pillow. There are candles. There are offerings. There is a guestbook.",
            "The pillow sits on a plinth, thorned and faintly crusted. The plaque reads 'HE WAS A GOOD PILLOW'.",
        ],
        "choices": [
            {
                "id": "sign_guestbook",
                "label": "✍️ Sign the guestbook",
                "description": "Be respectful. Or at least be brief.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.94,
                "success_text": "You write something kind. The shrine's collection box is unlocked, which feels like permission.",
                "on_success": {"gain": {"gold": [40, 80]}, "heal": 22},
                "fail_text": "You can't think of anything to write. You stand there. The moment passes.",
                "on_fail": {},
            },
            {
                "id": "touch_it",
                "label": "👉 Touch the pillow",
                "description": "It is visibly thorned and visibly crusted.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.45,
                "success_text": "Something in the shrine approves. You are given a blessing and asked, politely, to leave.",
                "on_success": {"gain": {"material_tier": 2, "amount": [7, 14], "gold": [90, 160]},
                               "bonus": {"chance": 0.11, "gain": {"lootbox": "rare"}}},
                "fail_text": "The thorns. The crust. Both, immediately.",
                "on_fail": {"hp_damage_percent": 15},
            },
            {
                "id": "leave_offering",
                "label": "🕯️ Leave an offering (40 gold)",
                "description": "When in Rome. When at a body pillow shrine.",
                "action": "trade",
                "style": "primary",
                "cost": {"gold": 40},
                "success_chance": 0.88,
                "success_text": "The shrine's keeper -- there is a keeper -- thanks you and points you at something worth having.",
                "on_success": {"gain": {"material_tier": 2, "amount": [5, 11], "gold": [70, 120]}},
                "fail_text": "Nobody appears. Your 40 gold sits on the plinth looking foolish.",
                "on_fail": {},
            },
        ],
    },
    {
        "id": "jynxzi_stream",
        "name": "Jynxzi Is Live",
        "image_url": None,
        "room_types": ["story", "secret"],
        "intros": [
            "A ring light, a tripod, and a man narrating your arrival to nine thousand people in real time.",
            "\"CHAT. CHAT. Look who it is.\" He has not stopped talking since you entered the room.",
        ],
        "choices": [
            {
                "id": "wave",
                "label": "👋 Wave at chat",
                "description": "Give the people what they want.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.92,
                "success_text": "Chat loves you. Donations are made. A cut is, remarkably, passed on to you.",
                "on_success": {"gain": {"gold": [60, 110]},
                               "bonus": {"chance": 0.08, "gain": {"shards": [1, 2]}}},
                "fail_text": "Chat does not love you. Chat has moved on to arguing about something else.",
                "on_fail": {},
            },
            {
                "id": "unplug",
                "label": "🔌 Unplug the ring light",
                "description": "End the stream. Take the light.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.55,
                "success_text": "The stream dies. Nine thousand people witness nothing further. The light is yours.",
                "on_success": {"gain": {"material_tier": 2, "amount": [6, 12], "gold": [80, 140]},
                               "bonus": {"chance": 0.1, "gain": {"reroll_tokens": [3, 6]}}},
                "fail_text": "He has a backup. He has three backups. The clip of you trying is already circulating.",
                "on_fail": {"hp_damage_percent": 7},
            },
            {
                "id": "backseat",
                "label": "🎮 Backseat him",
                "description": "Tell him, on stream, how to do his job.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.42,
                "success_text": "You're right, and chat never lets him forget it. He pays you to leave.",
                "on_success": {"gain": {"gold": [130, 220], "reroll_tokens": [2, 5]}},
                "fail_text": "You're wrong, on stream, in front of nine thousand people. The clip outlives you.",
                "on_fail": {"hp_damage_percent": 6},
            },
        ],
    },
    {
        "id": "billboard_apology",
        "name": "An Apologetic Billboard",
        "image_url": None,
        "room_types": ["story", "puzzle"],
        "intros": [
            "A false-advertising billboard is displaying, in enormous letters, 'WE ARE SORRY'.",
            "The billboard cycles through: 'WE ARE SORRY' / 'IT WAS NEVER 40% OFF' / 'PLEASE COME BACK'.",
        ],
        "choices": [
            {
                "id": "accept_apology",
                "label": "🕊️ Accept the apology",
                "description": "Everyone deserves a second chance. Even signage.",
                "action": "risk",
                "style": "success",
                "success_chance": 0.9,
                "success_text": "The billboard dispenses a genuine, honestly-priced product from a slot you hadn't noticed.",
                "on_success": {"gain": {"material_tier": 1, "amount": [9, 17], "gold": [45, 85]}},
                "fail_text": "It thanks you and immediately resumes advertising something that doesn't exist.",
                "on_fail": {},
            },
            {
                "id": "demand_refund",
                "label": "🧾 Demand a refund",
                "description": "You never bought anything. That's not the point.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.45,
                "success_text": "It processes a full refund for a purchase you never made. You do not question this.",
                "on_success": {"gain": {"gold": [160, 280]},
                               "bonus": {"chance": 0.1, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "It displays 'NO' at a size visible from orbit.",
                "on_fail": {},
            },
            {
                "id": "ignore_billboard",
                "label": "🚶 Walk past it",
                "description": "It's a sign. It'll be fine.",
                "action": "leave",
                "style": "secondary",
                "text": "You walk past without acknowledging it. Behind you it switches to 'PLEASE'.",
            },
        ],
    },
    {
        "id": "the_worst_merchant",
        "name": "Extremely Confident Merchant",
        "image_url": None,
        "room_types": ["merchant"],
        "intros": [
            "A merchant with one item, no stall, and the bearing of a man who has never been wrong.",
            "\"Best prices in the Cascade,\" he says, gesturing at a tarpaulin with a single object under it.",
        ],
        "choices": [
            {
                "id": "buy_mystery",
                "label": "🎁 Buy the thing under the tarp (200 gold)",
                "description": "He won't say what it is. He says that's the best part.",
                "action": "gamble",
                "style": "danger",
                "cost": {"gold": 200},
                "tiers": [
                    {"chance": 0.1, "text": "It's genuinely excellent. He was right. He is insufferable about it.",
                     "outcome": {"gain": {"item": "natural", "gold": [150, 260]}}},
                    {"chance": 0.25, "text": "It's a solid, useful piece of kit. Fair trade, honestly.",
                     "outcome": {"gain": {"material_tier": 2, "amount": [8, 15]}}},
                    {"chance": 0.4, "text": "It's fine. It's a bag of ordinary materials. You've been had, mildly.",
                     "outcome": {"gain": {"material_tier": 1, "amount": [6, 12]}}},
                    {"chance": 0.25, "text": "It's a rock. He maintains eye contact the entire time you look at it.",
                     "outcome": {"gain": {"material_tier": 0, "amount": [3, 7]}}},
                ],
            },
            {
                "id": "ask_questions",
                "label": "❓ Ask what it is",
                "description": "A reasonable request.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.3,
                "success_text": "He tells you. It's a rock. He gives you 80 gold to never mention this to anyone.",
                "on_success": {"gain": {"gold": [70, 90]}},
                "fail_text": "\"That,\" he says, \"would ruin it.\"",
                "on_fail": {},
            },
            {
                "id": "walk",
                "label": "🚶 Walk away",
                "description": "You have a bad feeling about the tarp.",
                "action": "leave",
                "style": "secondary",
                "text": "\"Your loss!\" he calls after you. It probably wasn't.",
            },
        ],
    },
    {
        "id": "sixty_seven",
        "name": "It's Just Standing There",
        "image_url": None,
        "room_types": ["trap", "story"],
        "intros": [
            "A very small figure stands in the middle of the corridor. It is not moving. It is labelled, in marker, '67'.",
            "It's about knee height. It has done nothing since you walked in. Your squad has quietly formed a semicircle around it.",
        ],
        "choices": [
            {
                "id": "poke_it",
                "label": "👉 Poke it",
                "description": "It's small. How bad could it be.",
                "action": "risk",
                "style": "danger",
                "success_chance": 0.5,
                "success_text": "It falls over. That's all it does. Under it is somebody's emergency stash.",
                "on_success": {"gain": {"gold": [110, 200], "material_tier": 2, "amount": [5, 11]},
                               "bonus": {"chance": 0.1, "gain": {"lootbox": "uncommon"}}},
                "fail_text": "It moves once. You do not see it move. You only see the aftermath.",
                "on_fail": {"hp_damage_percent": 20},
            },
            {
                "id": "back_away",
                "label": "🚶 Back away slowly",
                "description": "Your instincts are telling you something.",
                "action": "leave",
                "style": "success",
                "text": "You give it a wide berth. It watches you the entire way past, without moving. Good call.",
            },
            {
                "id": "salute",
                "label": "🫡 Salute it",
                "description": "Show respect to whatever this is.",
                "action": "risk",
                "style": "primary",
                "success_chance": 0.85,
                "success_text": "It salutes back. Something passes between you. It lets you take the stash under it.",
                "on_success": {"gain": {"gold": [70, 130], "material_tier": 1, "amount": [6, 13]}},
                "fail_text": "It does not salute back. The moment stretches. You leave.",
                "on_fail": {},
            },
        ],
    },
]
